services:
  api-nginx:
    build: ./services/api-nginx/
    ports:
      - "8181:80"

    volumes:
      - ./app/:/var/www/html/

  api-php:
    build: ./app/
    expose:
      - 9000
    volumes:
      - ./app/:/var/www/html/

  db:
    image: mariadb
    volumes:
      -    mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
    ports:
      - "4409:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "6969:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql-data: